### ISSUE TITLE
Local network sessions are not found.

### ISSUE THREAD

**Issue by STUVash** [wafflecomposite/LemnisGateSalvageOps#2]
I'm creating a session on one computer using the LAN setup stated in the github.
With the same setup copied onto another computer, when going in the game to join the session, no session can be found.

It's a shame, I like the game quite alot, went into Diamond 1 lvl 74 on release and felt like sharing the experience with friends on PC.
Guidance would be fairly appreciated, thanks for the hope.

**Comment by wafflecomposite** [comment]
Hey there, thanks for reaching out!

I assume you followed the LAN P2P setup from the manual. If anything seems off on the game or launcher side, I might not have the power to fix it since I didn't write the network code myself, and I can't really change it. However, I can reassure you that I've tested it extensively, and it's highly unlikely to be the source of the problem.

Here's what you can try:
- Set up different usernames in the `account_name.txt` file.
- Make sure you launch the game the same way on both sides, preferably through the `.exe` file. Using Steam to launch one of the clients might give the game a different ID.
- Triple check that you used the correct `steam_api64.dll`
- Try hosting from both PCs.

Most likely, it's a simple issue with your LAN connection not properly reaching the game port, which can happen for various reasons. If you're using Windows 10/11, here's a general list of things to check and try:

<details>
<summary>Click for LAN basic troubleshooting suggestions (further googling required for those)</summary>

- Make sure your firewall and antivirus aren't blocking the game.
- Check your router settings to ensure they're not causing any issues with connectivity.
- Test your connectivity with other tools or games that have reliable LAN functions.
- You can also consider trying tools like ZeroTier and Hamachi, even if your PCs are on the same network.

</details>

Glad you liked the game! If you've reached Diamond 1 rank, we might've crossed paths in a few matches.
Let me know if any of these did the trick.

**Comment by STUVash** [comment]
Oh wow, thanks for replying so fast !
I was thinking I'd be lucky if I'd get a response within a year but I guess you are 8760 times faster than expected.
I will give the setup a triple check next time my relative stops to use her computer for a bit.

- I tried with ZeroTier first with friends but since I don't know for sure if I'm doing everything right, I decided to try the local network instead. I'll try the "account_name.txt" change... I tried it with friends but not on local. Is the name in the menu supposed to change if we change the text in the "account_name.txt" file ? Because it didn't for my friends.
- Do I need to close steam for it to work properly when using the .exe ?
- The lan steam_api64.dll can't be mistaken I believe, it's the chonky one 1.86MB size from the DLL_LAN folder.
- I will try hosting from the other side too sure.
- Is the port number in "listen_port.txt" used for anything, should I open it ?
- I'm pretty sure I did the rest but I'll try next time, do we agree that if I see the computer on the network and can share files it should be fine ?

As for anything that does seem off, I copied the folder of my game from steam, it seems to have carried over the progress I had, including levels, rank, profile picture.
You made it seem to simple I feel so dumb that it's not working.
Maybe we did meet but ranking up was a bit too fast, I dunno if they ever fixed matchmaking but at the time of release you could be paired with Bronze5 while being Diamond.

**Comment by wafflecomposite** [comment]
- Visible name might not change, instead showing a PC name, it's a known bug but should not in any way affect the connectivity
- There should be no need to close Steam, but you can try that too as a last resort
- `.dll` size checks out, sure
- Yeah, that should be the port actually used for game discovery, so it should be open at firewall (or firewall disabled altogether), some weird routers might also limits the ports even inside the LAN network, but that's rather rare (and, again, can be bypassed with something like ZeroTier)
- Sharing being available is a really good sign, but unfortunately, it's still no guarantee that there is no problem with port availability. With LAN, you never know for sure :(

I don't quite get it, so you first copied the game, transferred it, and then modded it for LAN on both PCs separately, or you modded it for LAN and then copied it to another PC?

What's quite funny is that the progress is not saved to the game folder as far as I'm aware, so I'm not sure how you got it carried over. Might hint at some setup problem, might not, don't know what to make of it yet.

**Comment by STUVash** [comment]
I modded it for LAN and then copied it, aside from the Easy Anti Cheat uninstallation, it seems most of it was just replacing files in the game folder, am I wrong ?
Do you think I should log with my steam and download the game on that other computer and then do the whole modding ?

I gifted the game to a friend on release but he never tried it so I'm doing the testing with my own copy I got from steam.

**Comment by wafflecomposite** [comment]
Sounds ok. No need to redownload from Steam, files would be exactly the same.
If nothing above helps, and you have an option to log in to another steam account that has the game in it on a second PC, you can try going the Steam P2P way, I expect it to be more reliable for a local connection too, at the worst case it would provide a Steam relay to bypass possible restrictions.

**Comment by STUVash** [comment]
Alright, I think I got it.
I did one change, per booting up the game, meticulously until one change did make a difference at the end.

I already tried it before but it didn't give this result so maybe something else was wrong in the network at that time. The last change that made a difference between finding a match or not was having a different Steam id in the provided "user_steam_id.txt"
I didn't change that one because, somehow, the steam id provided was the one of a complete stranger, russian aswell. Since the youtube channel that posted the Salvaged Ops trailer was also russian, I thought the two were the same person or at least a dummy id needed for the mod, but this "user_steam_id.txt" was not in the Salvaged Ops archive, I have no idea why I had a random id.
And since it didn't come from the mod, the other users that didn't have an issue had their own "user_steam_id.txt" filled in with their own or another random one but most likely not identical ones to play together. Making sense there.

I had more ports opened but after that change made a difference I tried to put the firewall and router ports as before, on the local network it still works.
I'll try it tomorrow with the computer of my relative, and if it works there aswell, I'll try with my friends next.

I was gonna stay awake trying a couple more hours, I had wireshark watching what was happening on the network, I had x64dbg to look for breakpoints when refreshing the search for matches, ofc I'm not good enough to make sense of all that but I'm glad I reached a solution randomly Woohoo ! =o

**Comment by wafflecomposite** [comment]
So, I was actually wrong on all the suggestions. My bad.

Good find! I had no idea this was even a thing tbh.
My guess is that the steam emulation library generates some random Steam ID to use for the saves and networking, and then the API hides the lobby that have the same Steam ID so you won't accidentally matchmake with yourself. 
In your case, the file with ID then got copied with a game folder.

Should really make a note of that as it looks like a rather easy mistake to do. I will add this in the manual tomorrow. Thanks for investigating the problem, and have a good game!

**Comment by STUVash** [comment]
I managed to make it work online aswell, still didn't have a game yet we were just testing but they said we'd be playing in 4 days. Should be fun, thanks for the help.

**Comment by STUVash** [comment]
I managed to make it work online aswell, still didn't have a game yet we were just testing but they said we'd be playing in 4 days. Should be fun, thanks for the help.
