### ISSUE TITLE
Steam P2P lead to "Connection impossible" error

### ISSUE THREAD

**Issue by Digitalis87** [wafflecomposite/LemnisGateSalvageOps#3]
Hello Sir! 
First of all, I'd like to wish you all the best for the end of the year and, hopefully, a very happy Christmas/New Year too!
A few days ago, a friend and I wanted to play this gem of the video game industry and we stumbled across your repository. 

I'm coming to you today because, despite your tutorial, it's been impossible for us to play together, which is, I'm sure you'll agree, very sad. 

The error I've encountered is "Connection impossible" when one of us tries to join the other. We both have the game on steam, at version 1.3.26342 as required. 
We've tried so far: 
- Using steam P2P. We can find each other in the menus, but as soon as we want to join the other, it's impossible to connect to the other, regardless of the host.

- Using the patch you propose using the Steam method and not steam, nothing changes, we can find each other but not join.

-Deleted, deactivated EasyAntiCheat, no difference.

For further information, please do not hesitate to contact me! 
in the hope of finding a solution :)

**Comment by wafflecomposite** [comment]
Interesting. First time I hear about it, let alone see this myself, so no ideas at the moment.
Does it happen instantly when you trying to join, or there is some waiting? Can you share the screenshot?

**Comment by Digitalis87** [comment]
Hey, you're fast !

Nope, it does not happens instantly, we're having loading screens before the error message.

Worth to mention : We are both friends on stream showing up playing Lemnis Gate or Spacewar, i am having family mode disabled. 

We both have uninstalled the game sadly, so it will take a time to give you the screenshots.
What's feel strange is that both host does not works. I would understand better if only one of us could not host the party but...

**Comment by wafflecomposite** [comment]
Yeah, makes no sense to me. Game wasn't updated by devs since then, no untested changes to mod was done recently either, and even if you both have firewall active (try completely disabling it next time anyway), steam networking is supposed to bypass that.

I will try again on my machine, but I'm expecting to find it working exactly as before.

Quite a mystery. Sorry that it didn't worked.

**Comment by Digitalis87** [comment]
We're trying again my friend and i. What kind of software/logs can i use to give you a proper feedback of the issues we're facing ?

**Comment by Digitalis87** [comment]
All right, with firewall disabled it all works like intended, i also feel dumb to forget this possibility.... It all works fine ! Thanks a lot for your work, and your time !
