### ISSUE TITLE
Easy anti cheat auth error

### ISSUE THREAD

**Issue by AlanBadier** [wafflecomposite/LemnisGateSalvageOps#4]
Hello,

When we try to play with some friends (tried both LAN and Steam), we have the message "Easy anti cheat authentification timed out" and it closes the game (when the round switch to second player)

Any idea ?

P.S : Anticheat is uninstalled

Alan

**Comment by wafflecomposite** [comment]
That's something new, will have to investigate.
Does anticheat integrity warning shows when main menu is loaded? (It should)

Description is pretty much clear, but if you don't mind sharing a screenshot or a video of this happening, that might be useful too.

**Comment by wafflecomposite** [comment]
Right now I have no idea.
Only case that comes to mind (and it's a worst case), perhaps I missed that game was still sending some requests to some anticheat servers, and for some reason they could have been active until recently, but now they are turned off.
I hope not, that will be a pain to fix.

**Comment by AlanBadier** [comment]
I will do some testing and send you a screenshot if the problem occurs again, but I think we have fixed it by deleting anticheat folder
